### PR TITLE
Change refresh_spare_usr2 to use rsync

### PR DESCRIPTION
**Pull request by wehimwich**
@jfhquick suggested switching to _rsync_ to reduce the time required when _/usr2_ contains a lot of data. He also suggested that using _rrsync_ on the operational system may be a way to implement this with CIS hardening. These were both excellent suggestions. This PR is a first draft at making them work.

Summary of changes:

- Use _rsync_ in place of _tar_-based transfer.
- Move use of _mke2fs_ to option `-I`.
- Add option `-i` to trigger _rsync_ to transfer all files.
- Use _rrsync_ for CIS hardening.
- Make options that aren't for normal use uppercase.
- Update documents to agree.

These changes completely reorient the running of the script, simplifying it, and making routine use the same for both regular and CIS users. Special restrictions for using it are still required for the `-I` option.

There is some question whether the `-I` option is needed but perhaps it is worth keeping for possible recovery for some usual cases.  We can have it available as an option anyway. Likewise the `-i` option has limited utility, but may be useful to overcome possible issues with the modification time based quick check _rsync_ uses without requiring _mke2fs_.

I didn't see a way to make a good progress bar for foreground mode. Using `--info=progress2 --no-i-r` works pretty well, but there was no way to direct it only to the terminal, so it could make the log file unreasonably large. Instead, I used _pv_ in line mode to count the number of files and provide elapsed time. The resulting output may appear uneven because some files may be very large. There is no percentage of completion or ETA, but at least there is some feedback that the transfer is running.

Drafts of the updated sections in the documents can be found at [refresh_spare_usr2](https://nvi-inc.github.io/fsl10/draft_raid.html#_refresh_spare_usr2) and [Installing refresh_spare_usr2 with CIS hardening](https://nvi-inc.github.io/fsl10/draft_cis-setup.html#_installing_refresh_spare_usr2_with_cis_hardening). The embedded inks between the documents do not work.

The nominal plan is to install and test this in the field Sept 24.

### CODE REVIEW

**Comment by wehimwich** [comment]
Do'h. Sometimes the solution is so obvious, you can't see it. The `progress2` meter is now used in foreground. Some wording improvements were made. For foreground, I tried to defeat the `tee`'d and direct terminal output sometimes getting slightly out-of-order by using `stdbuf` twice; we'll see if that works or is worse than the disease.

The drafts docs were updated.

**Comment by wehimwich** [comment]
Every rock that is turned over exposes more stuff.

The non-CIS version should  use _rrsync_ as well. This is now included.  The installation instructions are now too large to fit easily into the script. The bulk of them are in the documents.

The draft documents have been updated (remember that the embedded links to the other docs don't work).

**Review by jfhquick — APPROVED** [review]
Two other things come to mind (to do with documentation only):
1.  It is possible to further tighten security on the ssh keyed login by adding a further 
         from="computer1,computer2"
    argument ahead of the command= argument in .ssh/authorized_keys.  Usually I use
    "alias,fqdn,ip" as it seems to be variable what sshd will accept.
2. As to running the script whilst the operational machine is in use, one can of course rerun the script at the end to catch up residual changes.

The script itself looks good, but it's complex enough that only running it  can confirm its OK.

**Comment by wehimwich** [comment]
Thanks for the feedback. I have added both of those points. I also pointed out that since the script usually runs pretty quickly, it normally should not be a significant burden to let it finish before logging in again.

I tested it fairly thoroughly, both for CIS and non-CIS. I can't guarantee there are no bugs of course, but it seems pretty reliable, especially for common cases.

**Pull request merged**
