### PR TITLE
Massively update refresh_spare_usr2

### PR DESCRIPTION
**Pull request by wehimwich**
I am putting just the script out for now without a document update. I would like to get to a nearly final version of the feaures before putting the effort in on the documents.

Summary of changes:

- Add a background mode with a log file, which is now the default.
- Use _pv_ for a progress meter in foreground mode.
- Send email message when done.
- Trap or explain all cases where being on _/usr2_ causes an issue.
- Reformat and reorganize messages using here document.
- Bring message content up to date.
- Add `Completed ...` message to mark end of executing critical code.
- Indent script written messages during refresh to make them standout.
- Add date/time commands to record when it started and how long it took.
- Simplify installation by not having to uncomment code.

The old script was very cumbersome in the CIS hardened environment, which it was never designed for. I prettied (not the original word I was going to use) it up to make it easier to use, more self explanatory, make a record of what happened, provide a progress meter, and brought the messages up to date. It is so different than the previous version, I think a `diff` is probably not very useful. It is however still built around Jon's original code for this task. I borrowed some ideas from Dave and web searches. Hopefully, it will be more usable for the non-CIS environment as well.

An advantage of the background mode is that the user can start it running, log-out, and walk away. An email is sent when it finishes. There is a saved copy of the log on disk. The thought is that the foreground mode might be used once to make sure it is working and see how long it takes, then background mode would be used after that.

 Some items to consider:

- The only way I was able to make the background mode work was to rerun the script with _nohup_ using a special argument to trigger doing the actual work. That seems okay. There are some gymnastics to avoid some warnings for I/O redirection from _nohup_. There may be better ways to do these things.
- It would be possible to have a log file for foreground use, but it seems _pv_ detects that it is not directly connected to a terminal and refuses to show the progress meter. I didn't want to give up having a progress meter for foreground mode.
- I resisted the temptation to add an option to remove the preamble messages and the confirmation to proceed. The script is used infrequently enough that I thought it was better to keep the operator in the loop. I ran it so many times for testing, such an option would have been useful.

Other possible improvements:

- Colorize the script's messages during a foreground refresh to make them standout more.
- Add an option to disable email.
- Other suggestions?

### CODE REVIEW

**Comment by wehimwich** [comment]
Now there is a log file for foreground with the progress meter on the terminal only. That wasn't too hard. :)

**Comment by wehimwich** [comment]
More changes:

- Replace preamble with short message.
- Add `-h` option for help, including old preamble and more information.
- Add `-s` option to suppress sending email.
- Add `-y` option to proceed without prompting for confirmation.
- Cleanup error processing for incorrect option use.
- Add that _ssh_ keys must be copied in install steps for background operation.
- Include some hints for CIS hardened system installation.
- Use more variables to completely remove the need to directly edit the (delicate) data transfer command when installing.
- Include whether refresh was background or foreground in log file.
- Clearly identify the _critical_ phase where an abort can cause trouble and provide steps for recovery.
- Replace `computer` and `machine` with `system` in comments and messages.
- Make various wording and formatting improvements.

The changes are a bit intertwined. I didn't think we would need to have small commits; so I didn't even try. That could always be revisited. Otherwise squashing and merging will probably be the right thing to do.

That is about it for now. That isn't to say it may not need either complete rewriting or various little changes.

**Comment by wehimwich** [comment]
I think I have worked through the issues with the different combinations of sessions: _root_/promoting-to-_root_, X/text-console, and _ssh_. Mostly this was in the description of `-h`.

Background mode would work for any situation. It is still disallowed for the user being on _/usr2_, but could be made to work by doing a _cd_ to a different partition just before launching the background job. However, the terminal gets messed up when the user is kicked out by _fuser_, requiring a _reset_ to recover. That is probably too unfriendly for regular users. The problem only happens if they are kicked back to a session they promoted to _root_ from (i.e., the session they promoted from was not on _/usr2_ and does not get kicked out). If they are logged out all together, including from just being _root_ on _/usr2_, the terminal doesn't have an issue. Unless there is a solution, it is  probably better to avoid this by continuing to disallow being on _/usr2_ for both modes.

**Review by jfhquick — CHANGES_REQUESTED** [review]
Overall a really nice rewrite to allow background usage.  Having a log file will be extremely helpful in case of there being issues at stations using this in future.  I didn't spot any obvious bloopers :-)  IMHO this is good to go.

So now you can attend to the documentation.

**Comment by wehimwich** [comment]
Thanks for the feedback. Github is telling me you requested changes, but I couldn't see any. Did you have any?

I have pushed a small increment on the `-h` text and draft changes to the _refresh_spare_usr2_ sections in the documents.  Those sections should now agree with new script. I converted (just) those sections to the FS font conventions. I simplified the formatting for the CIS installation case. Thinking that this script should now be a workhorse, I meant to get rid of the completely over-the-top use of admonitions for it in _raid.html_. In the end, I wasn't able to give up that bit of whimsy. :) You really should know what you are doing if you install it. :) The drafts can be view at:

https://nvi-inc.github.io/fsl10/draft_raid.html

https://nvi-inc.github.io/fsl10/draft_cis-setup.html

(I couldn't get the _drafts_ documents sub-directory approach that is used for the FS to work for FSL10. Perhaps that requires sourcing the `gh-pages` from the _docs_ sub-directory instead of the top-level. The side-effect of this is that any links in the draft documents to the others will take you to the current versions instead of the drafts.)

There is no hurry for any feedback. I am expecting to test the new script in the field at a station with CIS hardening on Sept 14. It may make sense to finalize it after that.

**Review by jfhquick — APPROVED** [review]

**Pull request merged**
