### PR TITLE
Add raid-events script

### PR DESCRIPTION
**Pull request by wehimwich**
Here is a suggestion for a means to send emails to report when RAID rebuilds start and end. It has been tested on four systems. It appears to handle both RAID rebuilds and RAID checks.

Sometimes for a rebuild started by _refresh_secondary_, the message for the start may be sent about 20 minutes late, but it is sent eventually.

### CODE REVIEW

**Comment by jfhquick** [comment]
It is most unusual to put an executable into /etc - the man page suggests /usr/sbin so in our case it should probably be in /usr/local/sbin like the other RAID support scripts.  You also react to _all_ events ie. a 3s wait even for the unrelated ones.

**Comment by wehimwich** [comment]
> It is most unusual to put an executable into /etc - the man page suggests /usr/sbin so in our case it should probably be in /usr/local/sbin like the other RAID support scripts.

I have changed the doc to have that. It isn't really a user or  a _root_ script, but it will behave reasonably if _root_ executes it. BTW, for easier reading, a _.html_ of the addition to doc is now available at:

https://nvi-inc.github.io/fsl10/draft_raid.html#_raid_events

> You also react to _all_ events ie. a 3s wait even for the unrelated ones.

The way I see it, is we have three options here:

1. Have a service that checks the status periodically.
2. Filter for just Rebuild events
3. What we have now.

Whichever of these options, or another, seems best is fine with me. I went with (3) for now because:

- I was not enamored with checking all the time, but that would probably get rid of the sometime (often?) 20 minute delay for getting the `Rebuild Running` message for _refresh_secondaty_. It would also mean that the _mdadm_ would never be delayed three seconds. Maybe the latter is the most important consideration.
- There aren't all that many events in total. I did not think it was much of an extra burden to have a few more waits.
- The events don't always seem to match the what we are interested in, so I started to think of them as just a chance to poll _/proc/mdstat_ to see if the state had changed. It is a little mysterious to me what is going on with event reporting. We  sometimes seem to get some out of order and not corresponding to what seems to be happening.

**Comment by jfhquick** [comment]
I'm a little leery of using another script under the hood.  If 'mdstat' is missing, this mechanism just fails silently whereas you could easily use 'cat /proc/mdstat` and achieve the required result.

I'm also intrigued by what I assume was a missing 'RebuildStarted' event and will keep fiddling on my test-beds with debug on until I can capture such an occurrence and try figure what might give rise to it.  So far I've not seen any unexpected or missed events from refresh_secondary or otherwise.  However it is clear that the monitoring process has a hotline to the kernel and sends our events before they are visible in /proc/mdstat.

**Comment by wehimwich** [comment]
I removed the use of the _mdstat_ script. I also added only running only when the event starts with `Rebuild`, that apparently did not cause the lose of any functionality. Also the `checkarray --cancel` needed `--all`.

Testing shows switching to background is not a good idea because you can get multiple copies of the background script running and thus multiple messages. Maybe a running copy could be tested for before starting another.

Still not getting _any_ kind of event immediately after running _refresh_secondary._  Messages for the Rebuild starting still come out, but ~20 minutes later. It may be the only way to overcome that is a service or test for an already running background script.

**Comment by wehimwich** [comment]
Testing for an already running background script isn't going to help if there are no events to trigger the script in the first place.

Being informed 20 minutes later doesn't seem that bad. It is better than not getting informed at all. :)

**Comment by wehimwich** [comment]
The branch was brought up to date with the change to FS font conventions in _master_.

For recent disk rotations on four systems running a draft of the script: one system reported the rebuild starting about 20 minutes "late"; the other three reported it "on time". The behavior seems to be variable.

The way the script is written now, if there isn't an event to trigger the `Running` message  either at the start or at 20 minutes after the start, it would be picked up by the  20% completion event, `Rebuild20`. Checking on the `Rebuild`: `20`, `40`, `63`, and `80` events could be eliminated by only checking for the `RebuildStarted` and `RebuildFinished` events.

**Comment by jfhquick** [comment]
I have now triggered a total of 20 rebuilds across 2 machines, half of which were checks.  In only 1 of the 20 was the first RebuildStarted event delayed by about 17 minutes - the other 19 times that event was generated immediately.  Possibly it is some sort of race condition between the background '/sbin/mdadm --monitor --scan' process and the /proc/mdstat kernel interface that it is polling.  Alternatively there may be a limit on how close together a Fail and a subsequent RebuildStarted event can be.

**Comment by wehimwich** [comment]
I limited the events it processes to  just `RebuildStartied` and `RebuildFinished`. A possible next step could be to try doing the real work in background again. That could avoid having the _mdadm_ daemon delayed up to three seconds in any case. With the processing limited to just the minimum events it may no longer be necessary to detect if a background instance is already running to avoid having multiple instances. 

> I have now triggered a total of 20 rebuilds across 2 machines, half of which were checks.  In only 1 of the 20 was the first RebuildStarted event delayed by about 17 minutes - the other 19 times that event was generated immediately.  Possibly it is some sort of race condition between the background '/sbin/mdadm --monitor --scan' process and the /proc/mdstat kernel interface that it is polling.  Alternatively there may be a limit on how close together a Fail and a subsequent RebuildStarted event can be.

I haven't done much much new testing, but in the past I have tried _rebuild_raid_ many, many, times and never saw the late `RebuildStarted`. I have tried _checkarray_ half-a-dozen times times or so and never saw late messages. It is hard to be definitive, but all this make me want to lean toward it being something about _rebuild_secondary_ again.

**Review by jfhquick — APPROVED** [review]
The occasional delayed RebuildStarted event issue lies elsewhere, so this pull rquest is good to go.  The use of an appendix in the documentation is a signifucant improvement

**Pull request merged**
