### PR TITLE
Allowing for possibility of LVM on top of RAID

### PR DESCRIPTION
**Pull request by jfhquick**
I have updated blank_secondary to clear any LVM found on a RAID before attempting to remove the RAID itself.  I didn't add "set -e" because I use some commands in ways that may fail at times, but softened the concluding statement to reflect that things may not have worked.

### CODE REVIEW

**Comment by edhimwich** [comment]
Do you think this should be tested both for clearing an i386 (Legacy) and amd64 (UEFI) disk or is one sufficient? Also does it need to be tested from both an i386 and amd64 primary? Possible combinations abound.

**Comment by jfhquick** [comment]
Hi Ed

I think whatever platform architecture you run it on is immaterial.  I would
also very much doubt that whether the disk to be blanked is Legacy or UEFI
bootable matters either.  However I'm not sure if I ever tried this on DOS
partition table - my descriptive header in the script only mentions GPT, but
then we only added support for DOS tables into refresh_secondary later.

When you do try test it. please run it first with the (hidden) '-v' verbose
option and see what it reports before aborting with <Control-C> at the first
prompt.  Then run it again but without that option and enter "y" to blank the
disk for real.

Thanks
 Jon

**Comment by wehimwich** [comment]
I tested this by blanking an fsl10 i386 install I had laying around. It seemed to work fine. I have attached two script output files (with **set -x**) in `blank_secondary`:

- [blank.txt](https://github.com/nvi-inc/fsl10/files/4659149/blank.txt), run with the -v option, 
- [blank2.txt](https://github.com/nvi-inc/fsl10/files/4659152/blank2.txt), the following run without -v

I could fairly easily do this on an amd64 install (probably just stopping after the partition table is set), if that would be useful.

**Comment by jfhquick** [comment]
Your tests showed the logic is correct, but in the process I thought of a serious flaw, namely that one needs to check that the volume group name differs from that on /dev/md0 before on gaily deletes it!  Will work on adding something suitable..

**Comment by jfhquick** [comment]
So the script now checks that the volume group it is cleaning up is different to that currently in use.  It also has a new '-n' dry run option which does (n)othing, best used with the (v)erbose option to ascertain whether it is going to do the right thing before actually doing it.

**Comment by wehimwich** [comment]
Two of four test cases:
[raid_dif.txt](https://github.com/nvi-inc/fsl10/files/4698925/raid_dif.txt)
[raid_sam.txt](https://github.com/nvi-inc/fsl10/files/4698926/raid_sam.txt)

**Comment by wehimwich** [comment]
Last two cases:
[nonraid_dif.txt](https://github.com/nvi-inc/fsl10/files/4703587/nonraid_dif.txt)
[nonraid_sam.txt](https://github.com/nvi-inc/fsl10/files/4703588/nonraid_sam.txt)

The check on the size of the second disk was very helpful.

Too bad the installer doesn't have an "abort (to shutdown)" in addition to the  "abort (to reboot)" option. That would have saved some flailing.

**Comment by wehimwich** [comment]
Test with RAID and same LV names:
[new_same.txt](https://github.com/nvi-inc/fsl10/files/4713866/new_same.txt)

BTW, `shutdown -h now` in a different VT of the installer still lead to a reboot. I was able to successfully shut it off with the power switch when it showed the second of the three BIOS splash screens (maybe that would have worked too if I had selected a normal **abort**; I haven't I tried it before).

**Pull request merged**
